package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "packaging",
    pip_version = "20.4",
    deps = [
        "//pip/pyparsing",
        "//pip/six",
    ],
)
