package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "attrs",
    pip_version = "21.4.0",
    provides = [
        "attr",
        "attrs",
    ],
    use_pep517 = True,
)
