package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "attrs",
    pip_version = "21.2.0",
    provides = ["attr"],
    use_pep517 = True,
)
