package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "attrs",
    pip_version = "19.3.0",
    provides = ["attr"],
    python2_compatible = True,
    python3_compatible = True,
    use_pep517 = True,
)
