package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "wcwidth",
    pip_version = "0.2.5",
    deps = ["//pip/backports.functools-lru-cache"],
)
