package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "wcwidth",
    pip_version = "0.1.7",
    python3_compatible = True,
)
