package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

licenses(["notice"])  # BSD

dbx_py_pypi_piplib(
    name = "pycparser",
    pip_version = "2.20",
)
