package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "atomicwrites",
    pip_version = "1.3.0",
    python3_compatible = True,
)
