package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "more_itertools",
    pip_version = "5.0.0",
    deps = ["//pip/six"],
)
