package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "typed-ast",
    pip_version = "1.4.0",
    provides = ["typed_ast"],
    deps = [],
)
