load("//build_tools/py:py.bzl", "dbx_py_library")

dbx_py_library(
    name = "runfiles",
    srcs = ["runfiles.py"],
    python3_compatible = True,
    validate = "strict",
    visibility = ["//visibility:public"],
)
