load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

dbx_py_pypi_piplib(
    name = "iniconfig",
    pip_version = "1.1.1",
    setup_requires = [
        "//pip/setuptools_scm",
    ],
    visibility = ["//visibility:public"],
)
