# @generated by //go/src/dropbox/build_tools/gen-build-go/gen-srcs

GO_GEN_BUILD_SRCS = [
    Label("//go/src/dropbox/build_tools/gen-build-go/lib:embed.go"),
    Label("//go/src/dropbox/build_tools/gen-build-go/lib:genbuildgolib.go"),
    Label("//go/src/dropbox/build_tools/gen-build-go/lib:godep.go"),
    Label("//go/src/dropbox/build_tools/gen-build-go/lib:tagmap.go"),
    Label("//go/src/dropbox/build_tools/gen-build-go/lib:targetlist.go"),
    Label("//go/src/dropbox/build_tools/gen-build-go/lib:utils.go"),
    Label("//go/src/dropbox/build_tools/gen-build-go:gen-build-go.go"),
    Label("//go/src/dropbox/build_tools/gen-build-go:go.mod"),
    Label("//go/src/dropbox/build_tools/gen-build-go:go.sum"),
]
