package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

licenses(["notice"])  # Python Software Foundation License

dbx_py_pypi_piplib(
    name = "typing",
    pip_version = "3.7.4.1",
    python2_compatible = True,
    python3_compatible = True,
)
