package(default_visibility = ["//visibility:public"])

load("//build_tools/py:py.bzl", "dbx_py_pypi_piplib")

licenses(["notice"])  # BSD

dbx_py_pypi_piplib(
    name = "flit-core",
    pip_version = "3.7.1",
    provides = ["flit_core"],
    use_pep517 = True,
)
