package junit

import (
	"bytes"
	"strings"
	"testing"
	"time"
)

func TestUpdateXML(t *testing.T) {
	cases := []struct {
		input    string
		duration time.Duration
		output   string
	}{
		{
			// Realistic XML output generated by py.test
			input:    `<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="0.050"><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="40" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.0018458366394"><system-err>foo</system-err></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.0262429714203"><system-err>bar</system-err></testcase></testsuite>`,
			duration: 5 * time.Second,
			// Changes from input: utf-8 -> UTF-8, time="0.050" -> time="5.000000", newline after XML header, add empty <properties></properties> and <test-artifacts></test-artifacts>
			output: `<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="5.000000"><properties></properties><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="40" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.0018458366394"><system-err>foo</system-err><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.0262429714203"><system-err>bar</system-err><properties></properties><test-artifacts></test-artifacts></testcase></testsuite>`,
		},
		{
			// A testcase with <error>
			input:    `<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="0.050"><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="40" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.0018458366394"><system-err>foo</system-err></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.0262429714203"><system-err>bar</system-err><error message="foo">bar</error></testcase></testsuite>`,
			duration: 5 * time.Second,
			// Changes from input: utf-8 -> UTF-8, time="0.050" -> time="5.000000", newline after XML header, add empty <properties></properties> and <test-artifacts></test-artifacts>
			output: `<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="5.000000"><properties></properties><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="40" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.0018458366394"><system-err>foo</system-err><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.0262429714203"><system-err>bar</system-err><properties></properties><error message="foo">bar</error><test-artifacts></test-artifacts></testcase></testsuite>`,
		},
		{
			// When given a set of test suites, just append a new testsuite
			input:    `<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="0.050"><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="40" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.0018458366394"><system-err>foo</system-err></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.0262429714203"><system-err>bar</system-err></testcase></testsuite></testsuites>`,
			duration: 5 * time.Second,
			// Changes from input: utf-8 -> UTF-8, newline after XML header, add empty <properties></properties> and <test-artifacts></test-artifacts>, add a new testsuite
			output: `<?xml version="1.0" encoding="UTF-8"?>
<testsuites time=""><testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="0.050"><properties></properties><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="40" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.0018458366394"><system-err>foo</system-err><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.0262429714203"><system-err>bar</system-err><properties></properties><test-artifacts></test-artifacts></testcase></testsuite><testsuite errors="0" failures="0" name="" skips="0" tests="0" time="5.000000"><properties></properties></testsuite></testsuites>`,
		},
		{
			// Single XML output generated by py.test with retry_cmd property
			input:    `<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="0.050"><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"><properties><property name="retry_cmd" value="--retry-ci=kdropbox/kiev/tests/test_selectors.py::test_invalid_percent"/></properties></testcase></testsuite>`,
			duration: 5 * time.Second,
			// Changes from input: utf-8 -> UTF-8, time="0.050" -> time="5.000000", newline after XML header, keep the retry_cmd property, and add empty <test-artifacts></test-artifacts>
			output: `<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="0" tests="3" time="5.000000"><properties></properties><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.0100638866425"><properties><property name="retry_cmd" value="--retry-ci=kdropbox/kiev/tests/test_selectors.py::test_invalid_percent"></property></properties><test-artifacts></test-artifacts></testcase></testsuite>`,
		},
		{
			// No header, no test methods
			input:    `<testsuite errors="0" failures="0" name="pytest" skips="0" tests="0" time="0"></testsuite>`,
			duration: 1 * time.Second,
			// Changes from input: add XML header, time="0.000" -> time="1.000000", add empty <properties></properties> and <test-artifacts></test-artifacts>
			output: `<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" name="pytest" skips="0" tests="0" time="1.000000"><properties></properties></testsuite>`,
		},
		{
			// Realistic py.test output for a failure
			input:    `<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="3" time="1.062"><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.00879907608032"></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="41" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.00247812271118"><system-err>foo</system-err></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.794937133789"><failure message="AssertionError: assert False">self = &lt;metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker testMethod=test_page_render_with_chrome_blocks_confirm_chromeless&gt;</failure><system-err>bar</system-err></testcase></testsuite>`,
			duration: 2 * time.Second,
			// Changes from input: utf-8 -> UTF-8, time="1.062" -> time="2.000000", newline after XML header, add empty <properties></properties> and <test-artifacts></test-artifacts>
			output: `<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="pytest" skips="0" tests="3" time="2.000000"><properties></properties><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.00879907608032"><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="41" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.00247812271118"><system-err>foo</system-err><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.794937133789"><failure message="AssertionError: assert False">self = &lt;metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker testMethod=test_page_render_with_chrome_blocks_confirm_chromeless&gt;</failure><system-err>bar</system-err><properties></properties><test-artifacts></test-artifacts></testcase></testsuite>`,
		},
		{
			// Realistic py.test output for a failure, including artifacts
			input:    `<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="3" time="1.062"><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.00879907608032"><test-artifacts><artifact name="artifact.txt" type="text" base64="dGVzdGluZwo=" /></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="41" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.00247812271118"><system-err>foo</system-err></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.794937133789"><failure message="AssertionError: assert False">self = &lt;metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker testMethod=test_page_render_with_chrome_blocks_confirm_chromeless&gt;</failure><system-err>bar</system-err></testcase></testsuite>`,
			duration: 2 * time.Second,
			// Changes from input: utf-8 -> UTF-8, time="1.062" -> time="2.000000", newline after XML header, add empty <properties></properties> and <test-artifacts></test-artifacts> for tests missing them
			output: `<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="1" name="pytest" skips="0" tests="3" time="2.000000"><properties></properties><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.00879907608032"><properties></properties><test-artifacts><artifact base64="dGVzdGluZwo=" name="artifact.txt" type="text"></artifact></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="41" name="test_file_viewer_component_render_with_chrome_blocks_confirm_chromeless" time="0.00247812271118"><system-err>foo</system-err><properties></properties><test-artifacts></test-artifacts></testcase><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="25" name="test_page_render_with_chrome_blocks_confirm_chromeless" time="0.794937133789"><failure message="AssertionError: assert False">self = &lt;metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker testMethod=test_page_render_with_chrome_blocks_confirm_chromeless&gt;</failure><system-err>bar</system-err><properties></properties><test-artifacts></test-artifacts></testcase></testsuite>`,
		},
	}

	for caseno, c := range cases {
		in := strings.NewReader(c.input)
		var out bytes.Buffer

		if err := OverwriteXMLDuration(in, c.duration, "", nil, &out); err != nil {
			t.Fatalf("Unexpected error overwriting XML")
		}

		if out.String() != c.output {
			t.Errorf("Output mismatch in Case #%d: Expected\n\n%s\n\nActual:\n\n%s\n\n", caseno, c.output, out.String())
		}
	}
}

func TestParseReruns(t *testing.T) {
	input := `<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="1" name="pytest" skips="0" tests="3" time="1.062"><testcase classname="metaserver.lib.tests.shared_link_chrome_checker_tests.TestSharedLinkChromeChecker" file="metaserver/lib/tests/shared_link_chrome_checker_tests.py" line="12" name="test_confirms_chromeless" time="0.00879907608032" rerun="2"></testcase></testsuite>`
	parsed, err := ParseAsSuites([]byte(input))
	if err != nil {
		t.Fatalf("should have parsed junit str, got %v", err)
	}
	if len(parsed.Suites) != 1 {
		t.Fatalf("should have received one suite, got %d", len(parsed.Suites))
	}
	if parsed.Suites[0].TestCases[0].Reruns() != 2 {
		t.Fatalf("should have two reruns, got %d", parsed.Suites[0].TestCases[0].Reruns())
	}
}
